// Package go19_testing 演示 Go 测试、基准测试与代码质量工具。
package go19_testing

import (
	"fmt"
	"strings"
)

// Demo 演示测试相关概念。
func Demo() {
	fmt.Println("========== go19_testing: 测试、基准与代码质量 ==========")
	fmt.Println()

	fmt.Println("--- 1. testing 基础：单元测试的基本结构 ---")
	fmt.Println("测试文件命名：*_test.go")
	fmt.Println("测试函数签名：func TestXxx(t *testing.T)")
	fmt.Println("运行测试：go test")
	fmt.Println("运行特定测试：go test -run TestAdd")
	fmt.Println("显示详细输出：go test -v")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func Add(a, b int) int { return a + b }")
	fmt.Println("  func TestAdd(t *testing.T) {")
	fmt.Println("      got := Add(2, 3)")
	fmt.Println("      want := 5")
	fmt.Println("      if got != want {")
	fmt.Printf("          t.Errorf(\"Add(2, 3) = %%v, want %%v\", got, want)\n")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 2. 表驱动测试：测试多组输入 ---")
	fmt.Println("表驱动测试用一个切片存储多组输入和预期输出，避免重复代码。")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  tests := []struct {")
	fmt.Println("      name string")
	fmt.Println("      a, b int")
	fmt.Println("      want int")
	fmt.Println("  }{")
	fmt.Println("      {\"正数\", 2, 3, 5},")
	fmt.Println("      {\"负数\", -1, -2, -3},")
	fmt.Println("      {\"零\", 0, 0, 0},")
	fmt.Println("  }")
	fmt.Println("  for _, tt := range tests {")
	fmt.Println("      got := Add(tt.a, tt.b)")
	fmt.Println("      if got != tt.want {")
	fmt.Printf("          t.Errorf(\"%%v: Add(%%v, %%v) = %%v, want %%v\",\n")
	fmt.Println("              tt.name, tt.a, tt.b, got, tt.want)")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 3. 子测试与 t.Run：独立的测试上下文 ---")
	fmt.Println("子测试让每组用例有自己的名字，失败时更容易定位。")
	fmt.Println("可以用 -run 只运行特定子测试。")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  for _, tt := range tests {")
	fmt.Println("      t.Run(tt.name, func(t *testing.T) {")
	fmt.Println("          got := Add(tt.a, tt.b)")
	fmt.Println("          if got != tt.want {")
	fmt.Printf("              t.Errorf(\"got %%v, want %%v\", got, tt.want)\n")
	fmt.Println("          }")
	fmt.Println("      })")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("运行特定子测试：go test -run TestAdd/正数")
	fmt.Println()

	fmt.Println("--- 4. t.Parallel：并行运行测试 ---")
	fmt.Println("调用 t.Parallel() 让测试并行运行，加快测试速度。")
	fmt.Println("注意：并行测试不能依赖全局状态或共享资源。")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func TestSlow(t *testing.T) {")
	fmt.Println("      t.Parallel() // 标记为可并行")
	fmt.Println("      time.Sleep(1 * time.Second)")
	fmt.Println("      // 测试逻辑")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("子测试也可以并行：")
	fmt.Println("  for _, tt := range tests {")
	fmt.Println("      tt := tt // 捕获循环变量（Go 1.22+ 不需要）")
	fmt.Println("      t.Run(tt.name, func(t *testing.T) {")
	fmt.Println("          t.Parallel()")
	fmt.Println("          // 测试逻辑")
	fmt.Println("      })")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 5. t.Helper / t.Cleanup / t.TempDir ---")
	fmt.Println()
	fmt.Println("t.Helper()：标记辅助函数，错误报告时跳过该函数的栈帧")
	fmt.Println("示例：")
	fmt.Println("  func assertEqual(t *testing.T, got, want int) {")
	fmt.Println("      t.Helper() // 错误时报告调用方的行号，而不是这一行")
	fmt.Println("      if got != want {")
	fmt.Printf("          t.Errorf(\"got %%v, want %%v\", got, want)\n")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("t.Cleanup(func())：注册清理函数，测试结束时自动调用")
	fmt.Println("示例：")
	fmt.Println("  func TestFile(t *testing.T) {")
	fmt.Println("      f, _ := os.Create(\"test.txt\")")
	fmt.Println("      t.Cleanup(func() { os.Remove(\"test.txt\") })")
	fmt.Println("      // 测试逻辑，无需手动删除文件")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("t.TempDir()：创建临时目录，测试结束时自动删除")
	fmt.Println("示例：")
	fmt.Println("  func TestWrite(t *testing.T) {")
	fmt.Println("      dir := t.TempDir() // 自动清理")
	fmt.Println("      path := filepath.Join(dir, \"file.txt\")")
	fmt.Println("      os.WriteFile(path, []byte(\"test\"), 0644)")
	fmt.Println("      // 测试逻辑")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 6. 基准测试与 -benchmem ---")
	fmt.Println("基准测试函数签名：func BenchmarkXxx(b *testing.B)")
	fmt.Println("运行基准测试：go test -bench=. -benchmem")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func BenchmarkAdd(b *testing.B) {")
	fmt.Println("      for i := 0; i < b.N; i++ {")
	fmt.Println("          Add(2, 3)")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("输出解读：")
	fmt.Println("  BenchmarkAdd-8  500000000  3.12 ns/op  0 B/op  0 allocs/op")
	fmt.Println("  含义：8 个 CPU、5 亿次操作、每次 3.12 纳秒、0 字节分配、0 次分配")
	fmt.Println()
	fmt.Println("b.ResetTimer()：重置计时器，排除初始化时间")
	fmt.Println("  func BenchmarkHeavy(b *testing.B) {")
	fmt.Println("      data := prepareData() // 初始化")
	fmt.Println("      b.ResetTimer()        // 重置计时器")
	fmt.Println("      for i := 0; i < b.N; i++ {")
	fmt.Println("          process(data)")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 7. 模糊测试（fuzzing）---")
	fmt.Println("模糊测试自动生成随机输入，找出边界情况和崩溃。")
	fmt.Println("模糊测试函数签名：func FuzzXxx(f *testing.F)")
	fmt.Println("运行模糊测试：go test -fuzz=FuzzAdd")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func FuzzAdd(f *testing.F) {")
	fmt.Println("      // 提供种子语料")
	fmt.Println("      f.Add(1, 2)")
	fmt.Println("      f.Add(-1, -2)")
	fmt.Println("      f.Fuzz(func(t *testing.T, a, b int) {")
	fmt.Println("          // 测试不应该 panic")
	fmt.Println("          result := Add(a, b)")
	fmt.Println("          // 验证性质：a + b == b + a")
	fmt.Println("          if result != Add(b, a) {")
	fmt.Println("              t.Errorf(\"交换律失败\")")
	fmt.Println("          }")
	fmt.Println("      })")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("模糊测试找到失败输入时，会保存到 testdata/fuzz/")
	fmt.Println()

	fmt.Println("--- 8. 示例测试 ---")
	fmt.Println("示例测试函数签名：func ExampleXxx()")
	fmt.Println("示例测试既是测试，也是文档。")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func ExampleAdd() {")
	fmt.Println("      fmt.Println(Add(2, 3))")
	fmt.Println("      // Output: 5")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("// Output: 注释指定预期输出，测试时会验证。")
	fmt.Println("示例会出现在 godoc 中，作为使用说明。")
	fmt.Println()

	fmt.Println("--- 9. 测试覆盖率 ---")
	fmt.Println("运行覆盖率：go test -cover")
	fmt.Println("生成覆盖率报告：go test -coverprofile=coverage.out")
	fmt.Println("查看 HTML 报告：go tool cover -html=coverage.out")
	fmt.Println()
	fmt.Println("输出示例：")
	fmt.Println("  ok      mypackage  0.123s  coverage: 85.7% of statements")
	fmt.Println()
	fmt.Println("覆盖率目标：通常 70-80% 是合理的，不必追求 100%。")
	fmt.Println("未覆盖的代码：错误处理分支、极端边界情况、不可达代码。")
	fmt.Println()

	fmt.Println("--- 10. httptest：测试 HTTP 处理器 ---")
	fmt.Println("httptest.ResponseRecorder：记录 HTTP 响应")
	fmt.Println("httptest.NewServer：创建测试用 HTTP 服务器")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  func TestHandler(t *testing.T) {")
	fmt.Println("      req := httptest.NewRequest(\"GET\", \"/hello\", nil)")
	fmt.Println("      rec := httptest.NewRecorder()")
	fmt.Println()
	fmt.Println("      handler(rec, req)")
	fmt.Println()
	fmt.Println("      if rec.Code != 200 {")
	fmt.Printf("          t.Errorf(\"status = %%v, want 200\", rec.Code)\n")
	fmt.Println("      }")
	fmt.Println("      if body := rec.Body.String(); body != \"Hello\" {")
	fmt.Printf("          t.Errorf(\"body = %%v, want %%v\", body, \"Hello\")\n")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 11. 接口打桩：依赖注入与测试替身 ---")
	fmt.Println("通过接口隔离外部依赖，测试时注入 mock 实现。")
	fmt.Println()
	fmt.Println("示例：")
	fmt.Println("  type UserStore interface {")
	fmt.Println("      GetUser(id int) (*User, error)")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  type FakeUserStore struct {")
	fmt.Println("      users map[int]*User")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func (s *FakeUserStore) GetUser(id int) (*User, error) {")
	fmt.Println("      if u, ok := s.users[id]; ok {")
	fmt.Println("          return u, nil")
	fmt.Println("      }")
	fmt.Println("      return nil, errors.New(\"not found\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func TestService(t *testing.T) {")
	fmt.Println("      store := &FakeUserStore{")
	fmt.Println("          users: map[int]*User{1: {Name: \"Alice\"}},")
	fmt.Println("      }")
	fmt.Println("      svc := NewService(store) // 注入 fake")
	fmt.Println("      // 测试 svc 的逻辑")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("--- 12. go vet / staticcheck / golangci-lint ---")
	fmt.Println()
	fmt.Println("go vet：内置静态分析工具")
	fmt.Println("  检查：未使用的变量、错误的格式化动词、不可达代码、死锁等")
	fmt.Println("  运行：go vet ./...")
	fmt.Println()
	fmt.Println("staticcheck：第三方静态分析工具")
	fmt.Println("  安装：go install honnef.co/go/tools/cmd/staticcheck@latest")
	fmt.Println("  运行：staticcheck ./...")
	fmt.Println("  检查项更多，包括性能、代码风格、安全问题")
	fmt.Println()
	fmt.Println("golangci-lint：聚合多种 linter")
	fmt.Println("  安装：go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest")
	fmt.Println("  运行：golangci-lint run")
	fmt.Println("  配置：.golangci.yml")
	fmt.Println("  推荐启用：errcheck、gosimple、govet、ineffassign、staticcheck、unused")
	fmt.Println()

	fmt.Println("========== 测试、基准与代码质量演示结束 ==========")
}

// Add 两数相加（用于测试示例）。
func Add(a, b int) int {
	return a + b
}

// Reverse 反转字符串（用于测试示例）。
func Reverse(s string) string {
	runes := []rune(s)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}

// IsPalindrome 判断是否为回文（用于测试示例）。
func IsPalindrome(s string) bool {
	s = strings.ToLower(s)
	return s == Reverse(s)
}

// Concat 拼接字符串（用于基准测试示例）。
func Concat(strs []string) string {
	result := ""
	for _, s := range strs {
		result += s
	}
	return result
}

// ConcatBuilder 用 strings.Builder 拼接（用于基准测试对比）。
func ConcatBuilder(strs []string) string {
	var b strings.Builder
	for _, s := range strs {
		b.WriteString(s)
	}
	return b.String()
}
